### PR TITLE
Add location attribute to forum

### LINKED ISSUE #1104: Add forum location property
- [x] User must be able to set its forum location in the forum form.
- [ ] The behavoir should be similar to Twitter's: we should suggest places, but the input is free. The list should show political areas such as neighborhood, state and country.
- [x] We should use an external API such as Google Maps API (I'm open to discuss this).
- [x] The data should be stored in a structure in which the system be able to find nearby forums.

### PR DESCRIPTION
**Pull request by jfresco**
New feature.
- The location should be entered in the new forum form.
- There is no autosuggestion capabilities right now.
- Location is normalized on server-side.
- Location is not shown in any place right now.

Closes #1104.

### CODE REVIEW

**Comment by slifszyc** [comment]
We should see this together again.

Errors when no location si found are not properly shown to the end user.

We should also change how this is shown to the user, more like:
screen shot 2015-11-09 at 12 19 12 pm
for countries only.

**Comment by slifszyc** [comment]
[country-flags](https://www.npmjs.com/package/country-flags) and [countries](https://www.npmjs.com/package/countries) might come in handy to build a new library for this I think

**Comment by jfresco** [comment]
The error handling is weak, but it was intended to be transparent to the user.
The idea is to have a textbox where the user can enter what he wants and, in the backend, try to normalize the user entry. Later, we can add an autocomplete.

Also, I think we shouldn't limit the user entry to countries only.

**Comment by mjlescano** [comment]
Closing the pull request because of staleness, we will keep the branch for future reference 💃

**Pull request closed without merging**
