### PR TITLE
Add Docker for development. Closes #1078

### LINKED ISSUE #1078: Docker for development
Following some recent conversations [on our gitter channel](https://gitter.im/DemocracyOS/app) I think it would be reasonable to provide a developer-friendly docker solution.

I have a pretty good idea about how we should address this, but I have some stuff I'd like to discuss.

Our main external dependency is `MongoDB`. This can be addressed in two ways:

1. Have a `MongoDB` server run inside the development container.
  * Pros
    * Running a local dev environment would just be `docker run -P democracyos-development`
    * [KISS](https://en.wikipedia.org/wiki/KISS_principle) FTW!
  * Cons
    * We'll have to decide whether to use one of the official `MongoDB` images as the base of our docker image (which has no useful tools like `vi` or `git`) or create (and maintain) a custom base image for our devs. In any case, our Dockerfile or docker build would be non-standard and require some complexity.
    * Unless we use an external dir for storing data, data would be los whenever the container is destroyed. And using external data dirs would also create a complexity by depending on the dev host's OS in some manner (e.g.: permission issues, etc.)

2. Have an additional container running `MongoDB` which we can link the dev container to.
  * Pros
    * Simple Dockerfile and setup process.
    * Dev container would be completely volatile with no risk of data loss.
  * Cons
    * We can't rely on `docker-compose` for orchestration since ATM it runs only on `OS/X`
    * Set-up will depend on people reding and following a guide under `README.md` or similar.

Thoughts?

### PR DESCRIPTION
**Pull request by gvilarino**
This will allow developers to have a running DemocracyOS environment, with build-watch-serve functionalities by just running `docker-compose up`.

### CODE REVIEW

**Comment by gvilarino** [comment]
@mjlescano I think this may be worthy of a minor release, right?

**Comment by mjlescano** [comment]
@gvilarino is it necessary to add `config/docker.json`? why don't use an ignored `development.json` as usual?

I'm also asking to have in mind a future production ready version of docker; we should add `production-docker.json` in that case?

**Comment by gvilarino** [comment]
Mainly because local development defaults don't work properly with docker link names. Basically, when running the app in a container, `mongodb` doesn't run on the same container, thus the URI can't be `mongodb://localhost` but needs to be `mongodb://mongodb-service-name`, which makes `defaults.json` not suitable for developing under `docker`.

An alternative to this would be to define the `docker`-specific config settings either via [`environment`](https://docs.docker.com/compose/compose-file/#environment) or [`env-file`](https://docs.docker.com/compose/compose-file/#env-file). Whichever the case, I think the better approach would be having a `docker` directory under the project root with all needed stuff for `docker` and `compose` to work properly (i.e.: having a separate `.env` file for `docker`, required `Dockerfile`s, etc.) and just leave a `docker-compose.yml` in the root project.

Makes sense?

**Comment by mjlescano** [comment]
yes! I like it much more, that way we don't pollute the `/config` folder, and don't create a new `docker` environment.

**Comment by gvilarino** [comment]
I think this one's ready @mjlescano - Please confirm. Protip: clean any existing workspace with `docker-compose down`

**Comment by gvilarino** [comment]
@jclagache @vladfr wanna check that out and see if it works for you?

**Comment by vladfr** [comment]
@gvilarino Hi! I ran it from `master` and it works like a charm.
My setup uses [Dinghy](https://github.com/codekitchen/dinghy) with VirtualBox on OSX 10.11.

**Comment by gvilarino** [comment]
@vladfr great news! I'm running with [docker beta](http://beta.docker.com) and it works well as well. Let us know if something comes up.

**Pull request merged**
